const bcrypt = require('bcrypt');

exports.seed = function (knex) {
	return knex('users')
		.then(function () {
			return knex('users').insert(

				// data generated by https://mockaroo.com/

				[
					{
						"first_name": "Curr",
						"last_name": "Ladley", "password": bcrypt.hashSync("4OTUUVDkYT", 8), "email": "asculpher0@independent.co.uk", "avatar": "avatars/superhero-1.png"
					},
					{
						"first_name": "Leopold",
						"last_name": "Varndall", "password": bcrypt.hashSync("5Pdb0nki8d0", 8), "email": "oivashkin1@nsw.gov.au", "avatar": "avatars/superhero-2.png"
					},
					{
						"first_name": "Brenna",
						"last_name": "Shwalbe", "password": bcrypt.hashSync("fskk612N0GR", 8), "email": "jmuldowney2@cargocollective.com", "avatar": "avatars/superhero-3.png"
					},
					{
						"first_name": "Grace",
						"last_name": "Eyer", "password": bcrypt.hashSync("Fq8wxfoXZLl", 8), "email": "lgunner3@tamu.edu", "avatar": "avatars/superhero-4.png"
					},
					{
						"first_name": "Idaline",
						"last_name": "Gounet", "password": bcrypt.hashSync("kIXb5qpu1z0", 8), "email": "balderton4@printfriendly.com", "avatar": "avatars/superhero-5.png"
					},
					{
						"first_name": "Sasha",
						"last_name": "Leys", "password": bcrypt.hashSync("xcPNPxHXOWTf", 8), "email": "aabazi5@nps.gov", "avatar": "avatars/superhero-6.png"
					},
				]
			);
		});
};
